# Generated by Django 4.1 on 2022-12-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='notes',
            new_name='body',
        ),
    ]
