# Generated by Django 4.1 on 2022-09-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_alter_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
