# Generated by Django 4.1 on 2022-10-04 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='author',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='hero.author'),
            preserve_default=False,
        ),
    ]
