# Generated by Django 4.1 on 2022-10-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0006_hero_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='author',
            name='screenName',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
