# Generated by Django 4.1 on 2022-10-16 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0009_alter_author_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='hero.author')),
                ('recipient', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='hero.author')),
            ],
        ),
    ]
