# Generated by Django 4.1 on 2022-11-04 03:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hero', '0010_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Investigator',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='author',
            new_name='investigator',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
