# Generated by Django 4.1 on 2022-11-25 19:33

from django.db import migrations, models
import django.db.models.deletion
import hero.models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0012_alter_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=hero.models.get_upload)),
            ],
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hero.photo'),
        ),
    ]
