# Generated by Django 4.1 on 2022-11-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0013_photo_alter_hero_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='image_url',
        ),
    ]
